### ISSUE TITLE
Adding extra languages

### ISSUE THREAD

**Issue by artelse** [BrianGilbert/QLColorCode-extra#4]
I want to add support for .coffee, .styl and .jade files. I tried editing the info.plist and language definition files in the plugin, but can't get it to work. Any ideas?

**Comment by artelse** [comment]
Answering my own question. I had to change load order of the QL plugins; 1.QLStephen 2.QLColorCode.

**Comment by BrianGilbert** [comment]
@artelse will you be sending a merge request?

**Comment by artelse** [comment]
Once I am happy with the coloring and finishing of the files, I'll make a merge available. Currently was  working just locally without git. Might be more than a week though due to work.
